<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net48;net8.0-windows;net10.0-windows</TargetFrameworks>
        <UseWpf>true</UseWpf>
    </PropertyGroup>

    <ItemGroup>
        <!--UI-->
        <PackageReference Include="CommunityToolkit.Mvvm"/>

        <!--Python-->
        <PackageReference Include="pythonnet"/>
        <PackageReference Include="IronPython"/>

        <!--MCP-->
        <PackageReference Include="ModelContextProtocol"/>

        <!--FSharp-->
        <PackageReference Include="FSharp.Core"/>
        <PackageReference Include="FSharp.Compiler.Service"/>

        <!--Logging-->
        <PackageReference Include="ZLogger"/>
        <PackageReference Include="ZLogger.Scintilla" />
        <PackageReference Include="Scintilla5.NET" Condition="$(TargetFramework.StartsWith('net4'))" /> <!-- Just to ensure unmanaged dlls copy to output -->

        <!--Ioc-->
        <PackageReference Include="Microsoft.Extensions.Hosting"/>

        <!-- Utils -->
        <PackageReference Include="System.Reflection.MetadataLoadContext"/>
        <PackageReference Include="System.Net.Http" Condition="$(TargetFramework.StartsWith('net4'))"/>
        <PackageReference Include="CliWrap"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DevTools.Settings\DevTools.Settings.csproj" />
        <ProjectReference Include="..\DevTools.UI\DevTools.UI.csproj" />
        <ProjectReference Include="..\DevTools.Logging\DevTools.Logging.csproj" />
        <ProjectReference Include="..\DevTools.Utilities\DevTools.Utilities.csproj" />
        <ProjectReference Include="..\DevTools.McpParser\DevTools.McpParser.csproj" />
        <ProjectReference Include="..\DevTools.Telemetry\DevTools.Telemetry.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="CommunityToolkit.Mvvm.ComponentModel" />
        <Using Include="CommunityToolkit.Mvvm.Input" />
        <Using Include="JetBrains.Annotations" />
        <Using Include="System" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\*.*" />
        <EmbeddedResource Include="Resources\scripts\*.*" />
    </ItemGroup>

</Project>
