<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit.v3"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
        <PackageReference Include="CliWrap"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\source\DevTools.Execution.Abstractions\DevTools.Execution.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="Fixtures\**\*" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>
