<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net48;net8.0-windows;net10.0-windows</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="OpenMcdf" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    </ItemGroup>

    <ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">
        <Reference Include="System.IO.Compression" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DevTools.FileMetadata.Core\DevTools.FileMetadata.Core.csproj" SetTargetFramework="TargetFramework=$(TargetFramework)" />
    </ItemGroup>

</Project>
