<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseAutoCad>true</UseAutoCad>
        <IsTestProject>true</IsTestProject>
        <HostName>Civil3D</HostName>
        <HostVersion>$(AutoCadVersion)</HostVersion>
        <ForceLaunch>false</ForceLaunch>
        <PerTestTimeout>60</PerTestTimeout>
        <LaunchTimeout>360</LaunchTimeout>
    </PropertyGroup>

    <Import Project="..\..\source\DevTools.TestAdapter\build\RevitDevTool.TestAdapter.targets"/>

    <ItemGroup>
        <PackageReference Include="NUnit"/>
        <ProjectReference Include="..\..\source\DevTools.TestAdapter\DevTools.TestAdapter.csproj"/>
    </ItemGroup>
</Project>
