<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <IsPackable>false</IsPackable>
        <GenerateTargetPlatformAttribute>false</GenerateTargetPlatformAttribute>
        <GenerateSupportedOSPlatformAttribute>false</GenerateSupportedOSPlatformAttribute>
        <NoWarn>$(NoWarn);CA1416</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit.v3"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
        <PackageReference Include="Microsoft.TestPlatform.ObjectModel"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\source\DevTools.NUnit.TestAdapter\DevTools.NUnit.TestAdapter.csproj"
                          AdditionalProperties="ILRepackable=false"/>
        <ProjectReference Include="..\DevTools.NUnit.Runtime.Fixtures\DevTools.NUnit.Runtime.Fixtures.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

</Project>
