<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <!--Ioc-->
        <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.9"/>
        <!--Python-->
        <PackageVersion Include="pythonnet" Version="3.0.5"/>
        <PackageVersion Include="IronPython" Version="3.4.2"/>
        <!--MCP-->
        <PackageVersion Include="ModelContextProtocol" Version="1.4.0"/>
        <!--FSharp-->
        <PackageVersion Include="FSharp.Core" Version="10.1.203"/>
        <PackageVersion Include="FSharp.Compiler.Service" Version="43.12.203"/>
        <!--CSharp-->
        <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0"/>
        <!--Telemetry-->
        <PackageVersion Include="Sentry" Version="6.5.0"/>
        <!--Logging-->
        <PackageVersion Include="ZLogger" Version="2.5.10"/>
        <PackageVersion Include="ZLogger.Scintilla" Version="0.0.6"/>
        <PackageVersion Include="Scintilla5.NET" Version="6.1.2"/> <!-- Just to ensure unmanaged dlls copy to output -->
        <!--Utilities-->
        <PackageVersion Include="System.Diagnostics.DiagnosticSource" Version="10.0.9"/>
        <PackageVersion Include="System.Reflection.MetadataLoadContext" Version="10.0.9"/>
        <PackageVersion Include="JetBrains.Annotations" Version="2025.2.4"/>
        <GlobalPackageReference Include="Polyfill" Version="10.7.0"/>
        <PackageVersion Include="Microsoft-WindowsAPICodePack-Shell" Version="1.1.5"/>
        <PackageVersion Include="System.Drawing.Common" Version="8.0.25"/>
        <PackageVersion Include="System.Net.Http" Version="4.3.4"/>
        <!--Console-->
        <PackageVersion Include="CliWrap" Version="3.10.2"/>
        <!--UI-->
        <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2"/>
        <PackageVersion Include="Microsoft.Web.WebView2" Version="1.0.3800.47"/>
        <!--Build Tools-->
        <PackageVersion Include="ILRepack" Version="2.0.44"/>
        <PackageVersion Include="Sourcy.DotNet" Version="1.1.1"/>
        <PackageVersion Include="Shouldly" Version="4.3.0"/>
        <PackageVersion Include="ModularPipelines" Version="3.2.8"/>
        <PackageVersion Include="ModularPipelines.Git" Version="3.2.8"/>
        <PackageVersion Include="ModularPipelines.DotNet" Version="3.2.8"/>
        <PackageVersion Include="ModularPipelines.GitHub" Version="3.2.8"/>
        <PackageVersion Include="Microsoft.VisualStudio.SolutionPersistence" Version="1.0.52"/>
        <!--File IO-->
        <PackageVersion Include="OpenMcdf" Version="3.1.4"/>
        <!--Revit Tasks (Testing only)-->
        <PackageVersion Include="Revit.Async" Version="2.1.1"/>
        <PackageVersion Include="ricaun.Revit.UI.Tasks" Version="1.0.1"/>
        <!--AutoCad-->
        <PackageVersion Include="ACadSharp" Version="3.6.12"/>
        <PackageVersion Include="ricaun.AutoCAD.UI" Version="0.5.0"/>
        <!--Tests-->
        <PackageVersion Include="coverlet.collector" Version="8.0.0"/>
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.3.0"/>
        <PackageVersion Include="xunit.v3" Version="3.2.2"/>
        <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5"/>
    </ItemGroup>
</Project>