<?xml version="1.0" encoding="UTF-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <!-- Revit -->
    <Import Condition="'$(UseRevit)' == 'true'" Project="$(MSBuildThisFileDirectory)props\Revit.props" />
    <Import Condition="'$(UseRevit)' == 'true'" Project="$(MSBuildThisFileDirectory)props\Revit.targets" />

    <!-- AutoCad -->
    <Import Condition="'$(UseAutoCad)' == 'true'" Project="$(MSBuildThisFileDirectory)props\AutoCad.props" />
    
    <!-- Civil3d -->
    <Import Condition="'$(UseCivil3d)' == 'true'" Project="$(MSBuildThisFileDirectory)props\Civil3d.props" />

    <!-- Navisworks -->
    <Import Condition="'$(UseNavisworks)' == 'true'" Project="$(MSBuildThisFileDirectory)props\Navisworks.props" />

</Project>
