[workspace]
authors = ["Inspexel"]
channels = ["conda-forge"]
name = "RevitDevTool"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
polars = "==1.44.1"
numpy = "==2.5.2"
openpyxl = "==3.1.5"
pydantic = "==2.13.5"
shapely = "==2.1.2"
scipy = "==1.18.0"
trimesh = "==5.0.0"
networkx = "==3.6.1"
scikit-learn = "==1.9.0"
debugpy = "==1.8.21"
pytest = "==9.1.1"
olefile = "==0.47"
mcp = "==2.1.1"
pixi-pycharm = "==0.0.12"
xlsxwriter = ">=3.2.9,<4"

[pypi-dependencies]
manifold3d = "==3.5.2"
python-fcl = "==0.7.0.11"
dotenv = ">=0.9.9, <0.10"

[feature.dev.dependencies]
ruff = "*"
