<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net8.0-windows;net10.0-windows</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>DevTools.Pytest</RootNamespace>
    <UseWPF>false</UseWPF>
    <PolyUseEmbeddedAttribute>true</PolyUseEmbeddedAttribute>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Polyfill">
      <ExcludeAssets>all</ExcludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevTools.Ipc\DevTools.Ipc.csproj" />
  </ItemGroup>
</Project>
