using System.Buffers;
using System.Runtime.CompilerServices;
using System.Text;
using Microsoft.Extensions.Logging;
using RevitDevTool.Scintilla.Render;
using ZLogger;
namespace RevitDevTool.Scintilla.Formatting;

/// <summary>
/// ZLogger <see cref="IZLoggerFormatter"/> optimised for the Scintilla log viewer.
/// </summary>
/// <remarks>
/// <para>
/// Produces compact UTF-8 output in the format:
/// <c>[HH:mm:ss.fff LVL] [Category] {message}\n</c>
/// </para>
/// <para>
/// The prefix structure is designed to match <c>TryBuildPrefixSegmentsFromUtf8</c> in
/// <see cref="LogRenderStrategy"/> exactly, guaranteeing the fast bytes-only style-colouring
/// path is always activated (no <c>Encoding.UTF8.GetString</c> call on the hot path).
/// </para>
/// <para>
/// All prefix bytes (timestamp, level, separators) are written via direct <see cref="IBufferWriter{T}"/>
/// calls using pre-encoded UTF-8 literals — zero string allocation.
/// The message body is written by calling <c>entry.ToString(writer)</c> which invokes ZLogger's
/// own UTF-8 interpolation path and is also allocation-free for value-type parameters.
/// </para>
/// </remarks>
internal sealed class ScintillaLogFormatter : IZLoggerFormatter
{
    // UTF-8 literals — compiled as ReadOnlySpan<byte> constants (no heap allocation).
    private static ReadOnlySpan<byte> OpenBracket      => "["u8;
    private static ReadOnlySpan<byte> CloseBracketSpace => "] "u8;
    private static ReadOnlySpan<byte> Space            => " "u8;
    private static ReadOnlySpan<byte> NewLine          => "\n"u8;

    // 3-char level abbreviations — must match ParseShortLevelBytes in LogRenderStrategy.
    private static ReadOnlySpan<byte> LevelTrc => "TRC"u8;
    private static ReadOnlySpan<byte> LevelDbg => "DBG"u8;
    private static ReadOnlySpan<byte> LevelInf => "INF"u8;
    private static ReadOnlySpan<byte> LevelWrn => "WRN"u8;
    private static ReadOnlySpan<byte> LevelErr => "ERR"u8;
    private static ReadOnlySpan<byte> LevelCrt => "CRT"u8;
    private static ReadOnlySpan<byte> LevelNon => "NON"u8;

    /// <summary>
    /// <see langword="false"/> — this formatter writes its own <c>\n</c> terminator.
    /// Stream-based ZLogger sinks should not add a second newline.
    /// </summary>
    public bool WithLineBreak => false;

    /// <inheritdoc />
    public void FormatLogEntry(IBufferWriter<byte> writer, IZLoggerEntry entry)
    {
        var info = entry.LogInfo; // LogInfo is a struct; copy is cheap (no class fields)

        // ── prefix: "[HH:mm:ss.fff LVL] " ───────────────────────────────────────
        // Total prefix = 1 + 12 + 1 + 3 + 2 = 19 bytes.
        writer.Write(OpenBracket);
        WriteTimestamp(writer, info.Timestamp.Utc);
        writer.Write(Space);
        writer.Write(GetLevelAbbreviation(info.LogLevel));
        writer.Write(CloseBracketSpace);

        // ── optional category: "[Category] " ────────────────────────────────────
        // LogCategory.Utf8Span is a ReadOnlySpan<byte> pre-encoded inside ZLogger — zero encoding cost.
        var categoryBytes = info.Category.Utf8Span;
        if (!categoryBytes.IsEmpty)
        {
            writer.Write(OpenBracket);
            writer.Write(categoryBytes);
            writer.Write(CloseBracketSpace);
        }

        // ── message body ─────────────────────────────────────────────────────────
        // entry.ToString(IBufferWriter<byte>) is ZLogger's zero-alloc UTF-8 message path.
        // For interpolated log calls generated by [ZLoggerMessage] or ZLog*, this writes
        // each parameter directly in UTF-8 without boxing or string creation.
        entry.ToString(writer);

        // ── exception ────────────────────────────────────────────────────────────
        var ex = info.Exception;
        if (ex is not null)
        {
            writer.Write(NewLine);
            WriteExceptionUtf8(writer, ex);
        }

        writer.Write(NewLine);
    }

    // Writes "HH:mm:ss.fff" — exactly 12 ASCII bytes, no allocation.
    // Layout expected by TryBuildPrefixSegmentsFromUtf8:
    //   index 0   = '['                         → Punctuation (1 byte)
    //   index 1-12 = "HH:mm:ss.fff"              → SecondaryText (12 bytes)
    //   index 13  = ' '                          → SecondaryText (1 byte, split point)
    //   index 14-16 = "INF"                      → Level style (3 bytes)
    //   index 17-18 = "] "                       → Punctuation (2 bytes)
    //   index 19+  = category + message          → Text
    private static void WriteTimestamp(IBufferWriter<byte> writer, DateTimeOffset ts)
    {
        var buf = writer.GetSpan(12);
        WriteTwoDigits(buf, 0, ts.Hour);
        buf[2]  = (byte)':';
        WriteTwoDigits(buf, 3, ts.Minute);
        buf[5]  = (byte)':';
        WriteTwoDigits(buf, 6, ts.Second);
        buf[8]  = (byte)'.';
        WriteThreeDigits(buf, 9, ts.Millisecond);
        writer.Advance(12);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteTwoDigits(Span<byte> buf, int offset, int value)
    {
        buf[offset]     = (byte)('0' + value / 10);
        buf[offset + 1] = (byte)('0' + value % 10);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void WriteThreeDigits(Span<byte> buf, int offset, int value)
    {
        buf[offset]     = (byte)('0' + value / 100);
        buf[offset + 1] = (byte)('0' + value / 10 % 10);
        buf[offset + 2] = (byte)('0' + value % 10);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static ReadOnlySpan<byte> GetLevelAbbreviation(LogLevel level) => level switch
    {
        LogLevel.Trace       => LevelTrc,
        LogLevel.Debug       => LevelDbg,
        LogLevel.Information => LevelInf,
        LogLevel.Warning     => LevelWrn,
        LogLevel.Error       => LevelErr,
        LogLevel.Critical    => LevelCrt,
        _                    => LevelNon
    };

    // Exception.ToString() allocates once — acceptable since exceptions are rare in log streams.
    // We encode the result directly into the writer without an intermediate byte[].
    private static void WriteExceptionUtf8(IBufferWriter<byte> writer, Exception ex)
    {
        var text = ex.ToString();
#if NET8_0_OR_GREATER
        var maxBytes = Encoding.UTF8.GetMaxByteCount(text.Length);
        var span = writer.GetSpan(maxBytes);
        var written = Encoding.UTF8.GetBytes(text.AsSpan(), span);
        writer.Advance(written);
#else
        var bytes = Encoding.UTF8.GetBytes(text);
        writer.Write(bytes);
#endif
    }
}
