<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit.v3"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
        <PackageReference Include="pythonnet"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
        <Using Include="DevTools.Execution.Abstractions"/>
        <Using Include="DevTools.Ipc"/>
        <Using Include="DevTools.Mcp.Models"/>
        <Using Include="DevTools.Mcp.Discovery"/>
        <Using Include="DevTools.Mcp.Routing"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\source\DevTools.Execution.Abstractions\DevTools.Execution.Abstractions.csproj" />
        <ProjectReference Include="..\..\source\DevTools.Ipc\DevTools.Ipc.csproj" />
        <ProjectReference Include="..\..\source\DevTools.Mcp\DevTools.Mcp.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ModelContextProtocol" />
    </ItemGroup>

</Project>
