<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseRevit>true</UseRevit>
        <IsTestProject>true</IsTestProject>
        <OutputType>Library</OutputType>
        <HostName>Revit</HostName>
        <HostVersion>$(RevitVersion)</HostVersion>
        <HostLaunch>false</HostLaunch>
        <HostTimeout>60</HostTimeout>
        <HostLaunchTimeout>360</HostLaunchTimeout>
    </PropertyGroup>

    <Import Project="..\..\source\DevTools.NUnit.TestAdapter\build\DevTools.NUnit.TestAdapter.targets"/>

    <ItemGroup>
        <Compile Include="..\DevTools.NUnit.SampleTests\HostSmokeTests.cs" Link="HostSmokeTests.cs"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Nice3point.Revit.Toolkit" VersionOverride="$(RevitVersion).*"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="NUnit"/>
        <ProjectReference Include="..\..\source\DevTools.NUnit.TestAdapter\DevTools.NUnit.TestAdapter.csproj"/>
    </ItemGroup>
</Project>
