<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseWpf>true</UseWpf>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <TargetFrameworks>net48;net8.0-windows;net10.0-windows</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="JetBrains.Annotations" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft-WindowsAPICodePack-Shell" Condition="$(TargetFramework.StartsWith('net4'))" />
    </ItemGroup>

</Project>
