<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseWpf>true</UseWpf>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="JetBrains.Annotations" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft-WindowsAPICodePack-Shell" />
        <PackageReference Include="Nice3point.Revit.Api.AdWindows" VersionOverride="$(RevitVersion).*" PrivateAssets="All" Condition="$(Configuration.Contains('Autodesk'))"/>
    </ItemGroup>

</Project>
