<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <RootNamespace>RevitDevTool.Logger</RootNamespace>
        <LangVersion>latestmajor</LangVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <!--Serilog-->
        <PackageReference Include="Serilog"/>
        <PackageReference Include="Serilog.Sinks.File"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions"/>
        <PackageReference Include="System.Text.Json"/>

        <!--Utils-->
        <PackageReference Include="JetBrains.Annotations" PrivateAssets="all"/>

    </ItemGroup>

</Project>