<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseRevit>true</UseRevit>
        <IsTestProject>true</IsTestProject>
        <HostName>Revit</HostName>
        <HostVersion>$(RevitVersion)</HostVersion>
        <ForceLaunch>false</ForceLaunch>
        <PerTestTimeout>60</PerTestTimeout>
        <LaunchTimeout>360</LaunchTimeout>
    </PropertyGroup>

    <Import Project="..\..\source\DevTools.TestAdapter\build\RevitDevTool.TestAdapter.targets"/>

    <ItemGroup>
        <PackageReference Include="Nice3point.Revit.Toolkit" VersionOverride="$(RevitVersion).*"/>
        <PackageReference Include="NUnit"/>
        <ProjectReference Include="..\..\source\DevTools.TestAdapter\DevTools.TestAdapter.csproj"/>
    </ItemGroup>
</Project>
