<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="Microsoft.Testing.Platform"/>
        <PackageReference Include="xunit.v3"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
        <GlobalPackageReference Remove="Polyfill"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\source\DevTools.NUnit.Mtp\DevTools.NUnit.Mtp.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

</Project>
