<Project>
    <Import Project="..\Directory.Build.props" />

    <PropertyGroup Condition="$([System.String]::Copy('$(MSBuildProjectName)').EndsWith('.Tests'))">
        <OutputType>Exe</OutputType>
        <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    </PropertyGroup>

    <PropertyGroup Condition="'$(UseMicrosoftCodeCoverage)' == 'true'">
        <TestingExtensionsProfile>Default</TestingExtensionsProfile>
        <EnableMicrosoftTestingExtensionsCodeCoverage>true</EnableMicrosoftTestingExtensionsCodeCoverage>
    </PropertyGroup>

    <ItemGroup Condition="'$(UseMicrosoftCodeCoverage)' == 'true'">
        <None Include="$(MSBuildThisFileDirectory)mstest-coverage.xml"
              CopyToOutputDirectory="PreserveNewest"
              Link="coverage.xml" />
    </ItemGroup>
</Project>
