<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseRevit>true</UseRevit>
        <ILRepackable>true</ILRepackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Nice3point.Revit.Toolkit" VersionOverride="$(RevitVersion).*"/>
        <PackageReference Include="NetTopologySuite" VersionOverride="2.6.0"/>
    </ItemGroup>

</Project>
