<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseRevit>true</UseRevit>
        <IsRepackable>true</IsRepackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Nice3point.Revit.Toolkit" VersionOverride="$(RevitVersion).*"/>
        <PackageReference Include="Revit.Async"/>
        <PackageReference Include="ricaun.Revit.UI.Tasks"/>
        <PackageReference Include="ILRepack"/>
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\..\source\RevitDevTool.Core\RevitDevTool.Core.csproj" />
    </ItemGroup>

</Project>