<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseRevit>true</UseRevit>
        <UseWpf>true</UseWpf>
        <UseWindowsForms>true</UseWindowsForms>
        <DeployRevitAddin>true</DeployRevitAddin>
    </PropertyGroup>

    <PropertyGroup>
        <IsRepackable>true</IsRepackable>
        <RepackBinariesExcludes>
            MahApps.Metro.dll;
            ControlzEx.dll;
            Microsoft.Xaml.Behaviors.dll;
            FSharp.Core.dll;
        </RepackBinariesExcludes>
    </PropertyGroup>

    <ItemGroup>
        <!--Build-->
        <PackageReference Include="ILRepack"/>

        <!--UI-->
        <PackageReference Include="CommunityToolkit.Mvvm"/>
        <PackageReference Include="MahApps.Metro"/>
        <PackageReference Include="Microsoft.Web.WebView2"  Condition="$(RevitVersion) &lt; 2024"/>

        <!--Python-->
        <PackageReference Include="pythonnet"/>

        <!--MCP-->
        <PackageReference Include="ModelContextProtocol"/>

        <!--FSharp-->
        <PackageReference Include="FSharp.Core"/>
        <PackageReference Include="FSharp.Compiler.Service"/>

        <!--Serilog-->
        <PackageReference Include="Serilog"/>
        <PackageReference Include="Serilog.Enrichers.Autodesk.Revit"/>
        <PackageReference Include="Serilog.Sinks.File"/>

        <!--Ioc-->
        <PackageReference Include="Microsoft.Extensions.Hosting"/>

        <!-- Utils -->
        <PackageReference Include="PolySharp" PrivateAssets="All" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive"/>
        <PackageReference Include="Microsoft-WindowsAPICodePack-Shell" Condition="$(TargetFramework.StartsWith('net4'))"/>
        <PackageReference Include="System.Reflection.MetadataLoadContext"/>
        <PackageReference Include="System.Net.Http" Condition="$(TargetFramework.StartsWith('net4'))"/>
        <PackageReference Include="System.Diagnostics.DiagnosticSource"/>
        <PackageReference Include="CliWrap"/>
    </ItemGroup>

    <ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">
        <Reference Include="System.IO.Compression" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\RevitDevTool.McpParser\RevitDevTool.McpParser.csproj" />
        <ProjectReference Include="..\Supports\PythonNetStubGenerator\PythonNetStubGenerator.csproj" />
        <ProjectReference Include="..\RevitDevTool.Core\RevitDevTool.Core.csproj" />
        <ProjectReference Include="..\Supports\Serilog.Sinks.RichTextBox.WinForms.Colored\Serilog.Sinks.RichTextBox.WinForms.Colored.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="CommunityToolkit.Mvvm.ComponentModel" />
        <Using Include="CommunityToolkit.Mvvm.Input" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\scripts\*.*" />
        <Resource Include="resources\icons\*.*"/>
    </ItemGroup>

    <!-- Start Revit -->
    <PropertyGroup>
        <StartAction>Program</StartAction>
        <StartProgram>C:\Program Files\Autodesk\Revit $(RevitVersion)\Revit.exe</StartProgram>
        <StartArguments>/language ENG</StartArguments>
    </PropertyGroup>

</Project>
