<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\source\DevTools.Hosting\DevTools.Hosting.csproj" SetTargetFramework="TargetFramework=net10.0-windows"/>
        <ProjectReference Include="..\..\source\DevTools.Hosting.Acad\DevTools.Hosting.Acad.csproj" SetTargetFramework="TargetFramework=net10.0-windows"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

</Project>
