<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <UseRevit>true</UseRevit>
        <NoWarn>$(NoWarn);MCPEXP001</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\DevTools.Mcp\DevTools.Mcp.csproj"/>
        <ProjectReference Include="..\RevitDevTool.Core\RevitDevTool.Core.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Content\**\*" />
    </ItemGroup>
</Project>
