<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseRevit>true</UseRevit>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Nice3point.Revit.Toolkit" VersionOverride="$(RevitVersion).*"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Condition="!$(TargetFramework.StartsWith('net4'))"/>
        <PackageReference Include="NUnit" VersionOverride="3.13.3"/>
        <PackageReference Include="ricaun.RevitTest.TestAdapter"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\DevTools.NUnit.SampleTests\HostSmokeTests.cs" Link="HostSmokeTests.cs"/>
    </ItemGroup>

    <!--Config NUnit-->
    <ItemGroup>
        <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
            <_Parameter1>NUnit.Open</_Parameter1>
            <_Parameter2>false</_Parameter2>
        </AssemblyAttribute>
        <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
            <_Parameter1>NUnit.Version</_Parameter1>
            <_Parameter2>$(RevitVersion)</_Parameter2>
        </AssemblyAttribute>
        <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
            <_Parameter1>NUnit.Close</_Parameter1>
            <_Parameter2>false</_Parameter2>
        </AssemblyAttribute>
    </ItemGroup>
</Project>