<?xml version="1.0" encoding="UTF-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <ItemGroup>
        <PackageReference Include="AutoCAD.NET" VersionOverride="$(AutoCadInternalVersion)" ExcludeAssets="runtime" />
    </ItemGroup>

    <ItemGroup Condition="'$(MSBuildProjectExtension)' != '.fsproj'">
        <Using Include="JetBrains.Annotations" />
        <Using Include="System" />
    </ItemGroup>

</Project>