<?xml version="1.0" encoding="UTF-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">


    <!-- ============================================== -->
    <!-- 1. Debug / Release Detection                   -->
    <!-- ============================================== -->

    <PropertyGroup Condition="'$(Configuration)' != 'Debug' AND $(Configuration.Contains('Debug'))">
        <DebugSymbols>true</DebugSymbols>
        <DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
    </PropertyGroup>

    <PropertyGroup
            Condition="'$(Configuration)' != 'Release' AND $(Configuration.Contains('Release'))">
        <Optimize>true</Optimize>
        <DebugType>portable</DebugType>
        <DefineConstants>$(DefineConstants);RELEASE</DefineConstants>
    </PropertyGroup>

    <!-- ============================================== -->
    <!-- 2. Deploy Bundle / Addin                       -->
    <!-- ============================================== -->

    <PropertyGroup>
        <DeployRevitAddin Condition="'$(DeployRevitAddin)' == ''">false</DeployRevitAddin>
        <PublishRevitAddin Condition="'$(DeployRevitAddin)' == 'true'">true</PublishRevitAddin>
        <PublishRevitAddin Condition="'$(PublishRevitAddin)' == ''">false</PublishRevitAddin>
    </PropertyGroup>

    <Target Name="PublishRevitAddinFiles"
            AfterTargets="Build"
            Condition="$(PublishRevitAddin) == 'true' AND '$(RevitVersion)' != ''">

        <ItemGroup>
            <PackageContentsFile Include="$(MSBuildThisFileDirectory)PackageContents.xml"/>
            <RevitAddinFile Include="$(ProjectDir)*.addin"/>
            <RevitBundleItems Include="$(TargetDir)**\*" Exclude="**\$(PublishDirName)\**\*"/>
            <_ResolvedFileToPublishAlways Include="@(Content)"
                                          PublishDirectory="%(Content.PublishDirectory)"
                                          Condition="'%(Content.CopyToPublishDirectory)' == 'Always'"/>
            <_ResolvedFileToPublishPreserveNewest Include="@(Content)"
                                                  PublishDirectory="%(Content.PublishDirectory)"
                                                  Condition="'%(Content.CopyToPublishDirectory)' == 'PreserveNewest'"/>
        </ItemGroup>

        <PropertyGroup>
            <BundleVersionDir>$(PublishDir)Contents\$(RevitVersion)\</BundleVersionDir>
        </PropertyGroup>

        <RemoveDir Directories="$(BundleVersionDir)" Condition="Exists('$(BundleVersionDir)')"/>

        <Copy SourceFiles="@(PackageContentsFile)"
              DestinationFolder="$(PublishDir)"/>
        <Copy SourceFiles="@(RevitAddinFile)"
              DestinationFolder="$(BundleVersionDir)"/>
        <Copy SourceFiles="@(RevitBundleItems)"
              DestinationFolder="$(BundleVersionDir)%(RecursiveDir)"/>
        <Copy SourceFiles="@(_ResolvedFileToPublishAlways)"
              SkipUnchangedFiles="false"
              DestinationFolder="$(BundleVersionDir)%(_ResolvedFileToPublishAlways.PublishDirectory)\%(RecursiveDir)"/>
        <Copy SourceFiles="@(_ResolvedFileToPublishPreserveNewest)"
              SkipUnchangedFiles="true"
              DestinationFolder="$(BundleVersionDir)%(_ResolvedFileToPublishPreserveNewest.PublishDirectory)\%(RecursiveDir)"/>

        <Message Text="$(AssemblyName) -> $(BundleVersionDir)" Importance="high"/>
    </Target>

    <Target Name="DeployRevitAddinFiles"
            AfterTargets="PublishRevitAddinFiles"
            Condition="$(DeployRevitAddin) == 'true' AND '$(RevitVersion)' != ''">

        <PropertyGroup>
            <BundleDestinationFolder Condition="'$(BundleDestinationFolder)' == ''">$(AppData)\Autodesk\ApplicationPlugins\$(MSBuildProjectName).bundle</BundleDestinationFolder>
            <BundleVersionDeployDir>$(BundleDestinationFolder)\Contents\$(RevitVersion)</BundleVersionDeployDir>
        </PropertyGroup>

        <RemoveDir Directories="$(BundleVersionDeployDir)" Condition="Exists('$(BundleVersionDeployDir)')"/>

        <ItemGroup>
            <RevitBundleDeployItems Include="$(PublishDir)**\*"/>
        </ItemGroup>

        <Copy SourceFiles="@(RevitBundleDeployItems)"
              SkipUnchangedFiles="false"
              DestinationFolder="$(BundleDestinationFolder)\%(RecursiveDir)"
              ContinueOnError="true"
              Retries="1"/>

        <Message Text="$(AssemblyName) -> $(BundleDestinationFolder)\" Importance="high"/>
    </Target>

    <Target Name="CleanRevitAddinFolder"
            AfterTargets="Clean"
            Condition="$(DeployRevitAddin) == 'true'">
        <RemoveDir Directories="$(BundleDestinationFolder)" ContinueOnError="true"/>
    </Target>

    <Target Name="CleanPublishFolder"
            AfterTargets="Clean"
            Condition="$(PublishRevitAddin) == 'true'">
        <RemoveDir Directories="$(PublishDir)"/>
    </Target>

    <!-- ============================================== -->
    <!-- 3. Define Constants                            -->
    <!-- ============================================== -->

    <Target Name="GenerateRevitCompatibleDefineConstants"
            BeforeTargets="CoreCompile"
            Condition="'$(RevitVersion)' != '' AND '$(DisableImplicitRevitDefines)' != 'true'">

        <PropertyGroup>
            <DefineConstants>$(DefineConstants);REVIT$(RevitVersion)</DefineConstants>
        </PropertyGroup>

        <PropertyGroup Condition="$(RevitVersion) &gt;= 2022">
            <DefineConstants>$(DefineConstants);REVIT2022_OR_GREATER</DefineConstants>
        </PropertyGroup>
        <PropertyGroup Condition="$(RevitVersion) &gt;= 2023">
            <DefineConstants>$(DefineConstants);REVIT2023_OR_GREATER</DefineConstants>
        </PropertyGroup>
        <PropertyGroup Condition="$(RevitVersion) &gt;= 2024">
            <DefineConstants>$(DefineConstants);REVIT2024_OR_GREATER</DefineConstants>
        </PropertyGroup>
        <PropertyGroup Condition="$(RevitVersion) &gt;= 2025">
            <DefineConstants>$(DefineConstants);REVIT2025_OR_GREATER</DefineConstants>
        </PropertyGroup>
        <PropertyGroup Condition="$(RevitVersion) &gt;= 2026">
            <DefineConstants>$(DefineConstants);REVIT2026_OR_GREATER</DefineConstants>
        </PropertyGroup>
        <PropertyGroup Condition="$(RevitVersion) &gt;= 2027">
            <DefineConstants>$(DefineConstants);REVIT2027_OR_GREATER</DefineConstants>
        </PropertyGroup>
    </Target>

</Project>