<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseRevit>true</UseRevit>
        <IsRepackable>true</IsRepackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ModelContextProtocol" />
        <PackageReference Include="ILRepack"/>
    </ItemGroup>

</Project>
