<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <AssemblyName>DependencyConsumer</AssemblyName>
        <IsPackable>false</IsPackable>
        <IsTestProject>false</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NUnit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GenerationPrivateDependency\GenerationPrivateDependency.csproj"/>
    </ItemGroup>

</Project>
