<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>DevTools.MSTest.MTP.Tests</RootNamespace>
    <AssemblyName>DevTools.MSTest.MTP.Tests</AssemblyName>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
    <IsTestingPlatformApplication>false</IsTestingPlatformApplication>
    <EnableMSTestRunner>false</EnableMSTestRunner>
    <UseMicrosoftTestingPlatformRunner>false</UseMicrosoftTestingPlatformRunner>
    <GenerateTestingPlatformEntryPoint>false</GenerateTestingPlatformEntryPoint>
    <StartupObject>DevTools.MSTest.MTP.Tests.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Fixtures\**\*.cs" />
    <EmbeddedResource Remove="Fixtures\**\*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\source\DevTools.MSTest.MTP\DevTools.MSTest.MTP.csproj" SetTargetFramework="TargetFramework=net48" />
    <ProjectReference Include="Fixtures\NoExecute\NoExecute.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>
</Project>
