<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseWpf>true</UseWpf>
        <UseRevit>true</UseRevit>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\DevTools.Execution.Abstractions\DevTools.Execution.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
        <PackageReference Include="System.Drawing.Common" ExcludeAssets="runtime"/>
    </ItemGroup>
</Project>
