<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <UseAutoCad>true</UseAutoCad>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\DevTools.Mcp.Catalog\DevTools.Mcp.Catalog.csproj" SetTargetFramework="TargetFramework=$(TargetFramework)" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Content\**\*" />
    </ItemGroup>
</Project>
