<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <UseAutoCad>true</UseAutoCad>
        <NoWarn>$(NoWarn);MCPEXP001</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\DevTools.Mcp\DevTools.Mcp.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Content\**\*" />
    </ItemGroup>
</Project>
