<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net8.0-windows;net10.0-windows</TargetFrameworks>
        <RootNamespace>DevTools.NUnit.Provider</RootNamespace>
        <AssemblyName>DevTools.NUnit.Provider</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.Reflection.Metadata" Condition="'$(TargetFramework)' == 'netstandard2.0'"/>
        <ProjectReference Include="..\DevTools.NUnit.Transport\DevTools.NUnit.Transport.csproj"/>
        <ProjectReference Include="..\DevTools.Testing.Abstractions\DevTools.Testing.Abstractions.csproj"/>
    </ItemGroup>
</Project>
