<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Desktop" />
        <PackageReference Include="Avalonia.Themes.Fluent" />
        <PackageReference Include="Avalonia.Fonts.Inter" />
        <PackageReference Include="Avalonia.Diagnostics">
            <IncludeAssets Condition="$(Configuration.Contains('Debug'))">All</IncludeAssets>
            <PrivateAssets Condition="$(Configuration.Contains('Debug'))">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="SukiUI" />
        <PackageReference Include="Material.Icons.Avalonia" />
        
        <!--Console-->
        <PackageReference Include="ConsoleAppFramework" />

        <!--Mvvm-->
        <PackageReference Include="CommunityToolkit.Mvvm" />

        <!-- Hosting and DI -->
        <PackageReference Include="Microsoft.Extensions.Hosting" />

        <!-- Logging -->
        <PackageReference Include="Serilog" />
        <PackageReference Include="Serilog.Sinks.File" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\RevitDevTool.Bridge\RevitDevTool.Bridge.csproj" />
      <ProjectReference Include="..\RevitDevTool.Console\RevitDevTool.Console.csproj" />
      <ProjectReference Include="..\RevitDevTool.Logger\RevitDevTool.Logger.csproj" />
      <Folder Include="Models\" />
      <Folder Include="Services\" />
      <Folder Include="ViewModels\" />
      <Folder Include="Views\" />
    </ItemGroup>
</Project>
