<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <IsPackable>false</IsPackable>
        <IsTestingPlatformApplication>false</IsTestingPlatformApplication>
        <EnableTUnitPolyfills>false</EnableTUnitPolyfills>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3"/>
        <PackageReference Include="Microsoft.Testing.Platform"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\source\DevTools.TUnit.Host\DevTools.TUnit.Host.csproj" SetTargetFramework="TargetFramework=net10.0-windows"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

</Project>
