<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net48;net8.0-windows;net10.0-windows</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DevTools.Logging\DevTools.Logging.csproj"/>
        <ProjectReference Include="..\DevTools.UI\DevTools.UI.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="JetBrains.Annotations"/>
        <Using Include="System"/>
    </ItemGroup>

</Project>
