"""
In-process MCP tool parser for Python.NET (mcp >= 1.26).

Only FastMCP servers are supported for static tool discovery.
The low-level mcp.server.lowlevel.Server does not expose a public API
for listing tools outside of an active session, so it is intentionally
excluded.

Public API only -- no private member access.
"""
import asyncio
import contextlib
import importlib.util
import inspect
import json
import sys
import traceback
import types
import uuid
from pathlib import Path
from typing import Any, Generator

from mcp.server.fastmcp import FastMCP
from mcp.types import Tool, ToolAnnotations


def _load_module(file_path: str) -> types.ModuleType:
    """Load a Python source file as an isolated module.

    Parameters
    ----------
    file_path:
        Absolute path to the ``.py`` file to load.

    Returns
    -------
    types.ModuleType
        The loaded module with a unique name to avoid registry collisions.

    Raises
    ------
    RuntimeError
        If the file cannot be located or its loader is unavailable.
    """
    name = f"rdt_parser_{uuid.uuid4().hex}"
    spec = importlib.util.spec_from_file_location(name, file_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load module: {file_path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _find_fastmcp_servers(module: types.ModuleType) -> list[FastMCP]:
    """Collect all ``FastMCP`` instances defined at module scope.

    Detection uses ``isinstance`` checks against the imported ``FastMCP``
    class -- no duck-typing or attribute probing.  ``vars(module)`` is used
    instead of ``inspect.getmembers`` to avoid triggering deprecated Pydantic
    instance-level descriptor access (``model_fields.__get__``).

    Parameters
    ----------
    module:
        A loaded Python module to scan.

    Returns
    -------
    list[FastMCP]
        Deduplicated list of ``FastMCP`` server instances found in the module.
    """
    seen: set[int] = set()
    result: list[FastMCP] = []

    def _collect(obj: object) -> None:
        if obj is None or inspect.isclass(obj) or id(obj) in seen:
            return
        if isinstance(obj, FastMCP):
            seen.add(id(obj))
            result.append(obj)

    get_fn = getattr(module, "get_mcp_server", None)
    if callable(get_fn):
        with contextlib.suppress(Exception):
            _collect(get_fn())

    for obj in vars(module).values():
        _collect(obj)

    return result


# Keys generated by Pydantic's JSON Schema that are internal bookkeeping
# and not part of the MCP input schema consumed by LLM clients.
_PYDANTIC_SCHEMA_INTERNAL_KEYS: frozenset[str] = frozenset({"$defs", "additionalProperties"})


def _strip_pydantic_internals(schema: dict[str, Any]) -> dict[str, Any]:
    """Remove Pydantic-internal JSON Schema keys irrelevant to MCP clients.

    Parameters
    ----------
    schema:
        Raw JSON Schema dict as produced by Pydantic.

    Returns
    -------
    dict[str, Any]
        Schema with ``$defs`` and ``additionalProperties`` removed.
    """
    return {k: v for k, v in schema.items() if k not in _PYDANTIC_SCHEMA_INTERNAL_KEYS}


def _annotations_to_dict(annotations: ToolAnnotations) -> dict[str, Any] | None:
    """Serialize ``ToolAnnotations`` to a plain dict.

    Uses Pydantic v2 ``model_dump()`` -- the canonical public serialization
    API.  Fields set to ``None`` by the tool author are excluded.

    Parameters
    ----------
    annotations:
        The ``ToolAnnotations`` instance to serialize.

    Returns
    -------
    dict[str, Any] or None
        Serialized annotations, or ``None`` when no fields are set.
    """
    dumped: dict[str, Any] = annotations.model_dump(exclude_none=True)
    return dumped if dumped else None


def _build_definition(tool: Tool, server_name: str, source_path: str) -> dict[str, Any]:
    """Build a tool definition dict from a ``mcp.types.Tool`` instance.

    Parameters
    ----------
    tool:
        Protocol-level tool object returned by ``FastMCP.list_tools()``.
    server_name:
        Human-readable name of the owning server (used as ``containerType``).
    source_path:
        Absolute path to the ``.py`` file that defines the tool.

    Returns
    -------
    dict[str, Any]
        Flat dict matching the ``McpToolDefinition`` C# contract.
    """
    raw_schema: dict[str, Any] = tool.inputSchema if isinstance(tool.inputSchema, dict) else {}
    input_schema = _strip_pydantic_internals(raw_schema)

    # tool.title is defined on BaseMetadata (mcp >= 1.26)
    title: str | None = tool.title
    annotations = tool.annotations
    annotations_dict: dict[str, Any] | None = (
        _annotations_to_dict(annotations) if annotations is not None else None
    )
    # ToolAnnotations.title takes precedence when tool.title is absent
    if title is None and annotations is not None and annotations.title is not None:
        title = annotations.title

    return {
        "name": tool.name,
        "displayName": title if title is not None else tool.name,
        "description": (tool.description or "").strip(),
        "inputSchemaJson": json.dumps(input_schema),
        "sourceKind": "Python",
        "containerType": server_name,
        "methodName": tool.name,
        "sourcePath": source_path,
        "annotations": annotations_dict,
    }


def _extract_fastmcp_tools(server: FastMCP, source_path: str) -> list[dict[str, Any]]:
    """Extract tool definitions from a ``FastMCP`` server instance.

    Parameters
    ----------
    server:
        The ``FastMCP`` instance to query.
    source_path:
        Absolute path to the ``.py`` file that owns the server.

    Returns
    -------
    list[dict[str, Any]]
        Tool definition dicts ready for JSON serialization.
    """
    tools: list[Tool] = asyncio.run(server.list_tools())
    server_name: str = server.name if server.name else "FastMCP"
    return [_build_definition(t, server_name, source_path) for t in tools]


def _iter_tool_files(toolset_path: Path) -> Generator[Path, None, None]:
    """Yield ``.py`` files to scan for FastMCP servers.

    Files whose names start with ``_`` (e.g. ``__init__.py``) are skipped.

    Parameters
    ----------
    toolset_path:
        Either a single ``.py`` file or a directory to search recursively.

    Yields
    ------
    Path
        Absolute paths to candidate ``.py`` files.
    """
    if toolset_path.is_file():
        if not toolset_path.name.startswith("_"):
            yield toolset_path
        return
    for py_file in sorted(toolset_path.rglob("*.py")):
        if not py_file.name.startswith("_"):
            yield py_file


def _extract_from_file(
    py_file: Path,
    root_dir: Path,
    seen_servers: set[int],
) -> list[dict[str, Any]]:
    """Load one ``.py`` file and extract all FastMCP tool definitions.

    The file's parent directory and ``root_dir`` are temporarily prepended
    to ``sys.path`` so that relative imports inside the toolset resolve
    correctly, then removed afterwards.

    Parameters
    ----------
    py_file:
        Path to the ``.py`` file to load.
    root_dir:
        Root directory of the toolset (added to ``sys.path``).
    seen_servers:
        Mutable set of already-processed server ``id``\\s used for
        deduplication across files.

    Returns
    -------
    list[dict[str, Any]]
        Tool definition dicts from all FastMCP servers found in the file,
        or an empty list if loading or extraction fails.
    """
    inserted: list[str] = []
    for p in (str(root_dir), str(py_file.parent)):
        if p not in sys.path:
            sys.path.insert(0, p)
            inserted.append(p)
    try:
        mod = _load_module(str(py_file))
        tools: list[dict[str, Any]] = []
        for server in _find_fastmcp_servers(mod):
            if id(server) in seen_servers:
                continue
            seen_servers.add(id(server))
            tools.extend(_extract_fastmcp_tools(server, str(py_file)))
        return tools
    except Exception:  # noqa: BLE001
        traceback.print_exc()
        return []
    finally:
        for p in inserted:
            with contextlib.suppress(ValueError):
                sys.path.remove(p)


def parse_directory(toolset_path: str) -> str:
    """Parse a toolset directory and return tool definitions as JSON.

    Scans all non-private ``.py`` files under ``toolset_path`` for
    ``FastMCP`` server instances and collects their registered tools.

    Parameters
    ----------
    toolset_path:
        Path to a directory containing ``.py`` toolset files, or a path
        to a single ``.py`` file.

    Returns
    -------
    str
        JSON array of tool definition objects matching the
        ``McpToolDefinition`` C# contract.
    """
    root = Path(toolset_path)
    root_dir: Path = root.parent if root.is_file() else root
    seen_servers: set[int] = set()
    all_tools: list[dict[str, Any]] = []

    for py_file in _iter_tool_files(root):
        all_tools.extend(_extract_from_file(py_file, root_dir, seen_servers))

    return json.dumps(all_tools)
