<Project Sdk="Microsoft.NET.Sdk">



    <PropertyGroup>

        <TargetFrameworks>net48;net8.0-windows;net10.0-windows</TargetFrameworks>

    </PropertyGroup>



    <PropertyGroup Condition="'$(TargetFramework)' == 'net48'">

        <PublishAot>false</PublishAot>

        <PublishTrimmed>false</PublishTrimmed>

        <SelfContained>false</SelfContained>

    </PropertyGroup>



    <PropertyGroup Condition="$(Configuration.Contains('Release'))">

        <DebugType>none</DebugType>

        <DebugSymbols>false</DebugSymbols>

    </PropertyGroup>



    <ItemGroup>

        <ProjectReference Include="..\DevTools.Execution.Abstractions\DevTools.Execution.Abstractions.csproj" />

        <ProjectReference Include="..\DevTools.Ipc\DevTools.Ipc.csproj" />

        <ProjectReference Include="..\DevTools.Mcp\DevTools.Mcp.csproj" />

    </ItemGroup>



    <ItemGroup>

        <Using Include="DevTools.Execution.Abstractions" />

        <Using Include="DevTools.Ipc" />

        <Using Include="DevTools.Mcp" />

        <Using Include="DevTools.Mcp.Models" />

    </ItemGroup>



    <ItemGroup>

        <PackageReference Include="CliWrap"/>

        <PackageReference Include="System.Diagnostics.DiagnosticSource"/>

        <PackageReference Include="System.Reflection.MetadataLoadContext"/>

        <PackageReference Include="ModelContextProtocol"/>

    </ItemGroup>



</Project>

