<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UseRevit>true</UseRevit>
    <IsTestProject>true</IsTestProject>
    <TestingFramework>tunit</TestingFramework>
    <HostName>Revit</HostName>
    <HostVersion>$(RevitVersion)</HostVersion>
    <ForceLaunch>false</ForceLaunch>
    <PerTestTimeout>60</PerTestTimeout>
    <LaunchTimeout>360</LaunchTimeout>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nice3point.Revit.Toolkit" VersionOverride="$(RevitVersion).*"/>
    <PackageReference Include="TUnit"/>
    <PackageReference Include="RevitDevTool.TestAdapter"/>
  </ItemGroup>
</Project>
