<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <IsPackable>false</IsPackable>
        <IsTestingPlatformApplication>false</IsTestingPlatformApplication>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Testing.Platform"/>
        <PackageReference Include="xunit.v3"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\source\DevTools.TestAdapter\DevTools.TestAdapter.csproj">
            <PrivateAssets>all</PrivateAssets>
            <AdditionalProperties>ILRepackable=false</AdditionalProperties>
        </ProjectReference>
        <ProjectReference Include="..\..\source\DevTools.Testing.Abstractions\DevTools.Testing.Abstractions.csproj"/>
        <ProjectReference Include="..\..\source\DevTools.Testing.Transport\DevTools.Testing.Transport.csproj"/>
        <ProjectReference Include="..\..\source\DevTools.NUnit.MTP\DevTools.NUnit.MTP.csproj" SetTargetFramework="TargetFramework=net10.0-windows">
            <PrivateAssets>all</PrivateAssets>
        </ProjectReference>
        <Compile Include="..\DevTools.Testing.Abstractions.Tests\PassThroughRunMapper.cs" Link="PassThroughRunMapper.cs" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

</Project>
