<Project Sdk="MSTest.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <IsPackable>false</IsPackable>
        <UseMicrosoftCodeCoverage>true</UseMicrosoftCodeCoverage>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\source\DevTools.Utilities\DevTools.Utilities.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting"/>
    </ItemGroup>

</Project>
