<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net8.0-windows;net10.0-windows</TargetFrameworks>
    <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
    <RootNamespace>DevTools.MSTest.MTP</RootNamespace>
    <AssemblyName>DevTools.MSTest.MTP</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
    <IsTestingPlatformApplication>false</IsTestingPlatformApplication>
    <EnableMSTestRunner>false</EnableMSTestRunner>
    <GenerateTestingPlatformEntryPoint>false</GenerateTestingPlatformEntryPoint>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="MSTest.TestFramework" Version="4.4.1" />
    <PackageVersion Include="MSTest.TestAdapter" Version="4.4.1" />
    <PackageReference Include="MSTest.TestFramework">
      <ExcludeAssets>analyzers</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="MSTest.TestAdapter">
      <ExcludeAssets>analyzers</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Testing.Platform" />
    <ProjectReference Include="..\DevTools.Testing.Abstractions\DevTools.Testing.Abstractions.csproj">
      <SetTargetFramework>TargetFramework=$(TargetFramework)</SetTargetFramework>
    </ProjectReference>
  </ItemGroup>

  <Target Name="RemoveMSTestAnalyzers" BeforeTargets="CoreCompile">
    <ItemGroup>
      <Analyzer Remove="@(Analyzer)" Condition="$([System.String]::Copy('%(Filename)').StartsWith('MSTest'))" />
    </ItemGroup>
  </Target>
</Project>
