import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    { type: 'category', label: 'Getting Started', collapsed: false, items: ['intro', 'getting-started/installation'] },
    {
      type: 'category',
      label: 'Execution',
      className: 'sidebar-group sidebar-group--execution',
      collapsed: false,
      items: [
        'execution/Execution-Overview',
        'execution/NuGet-Dependencies',
        'execution/Python-Dependencies',
        { type: 'category', label: 'Python', className: 'sidebar-icon sidebar-icon--python', items: [
          'execution/python/Execution-Python',
          'execution/python/Execution-PythonEcosystems',
          'execution/python/Execution-StubGeneration',
        ] },
        { type: 'category', label: 'IronPython', className: 'sidebar-icon sidebar-icon--ironpython', items: [
          { type: 'doc', id: 'execution/ironpython/Execution-VsPyRevit', label: 'pyRevit' },
          { type: 'doc', id: 'execution/ironpython/Execution-IronPythonStandalone', label: 'Standalone' },
        ] },
        { type: 'doc', id: 'execution/csharp-script/Execution-CSharp', label: 'C# Scripts', className: 'sidebar-icon sidebar-icon--csharp' },
        { type: 'doc', id: 'execution/fsharp-script/Execution-FSharp', label: 'F# Scripts', className: 'sidebar-icon sidebar-icon--fsharp' },
        { type: 'doc', id: 'execution/dotnet-assembly/Execution-Assembly', label: '.NET Assembly', className: 'sidebar-icon sidebar-icon--dotnet' },
        { type: 'doc', id: 'execution/python/Execution-PythonDebugging', label: 'Attach Debugger', className: 'sidebar-icon sidebar-icon--debugger' },
      ],
    },
    { type: 'category', label: 'Testing', className: 'sidebar-group sidebar-group--testing', items: [
      'testing/Testing-Overview',
      { type: 'category', label: 'Microsoft Testing Platform', className: 'sidebar-icon sidebar-icon--microsoft', items: [
        { type: 'doc', id: 'testing/NUnit', className: 'sidebar-icon sidebar-icon--nunit' },
        { type: 'doc', id: 'testing/TUnit', className: 'sidebar-icon sidebar-icon--tunit' },
      ] },
      { type: 'category', label: 'Python Test', className: 'sidebar-icon sidebar-icon--python', items: [
        { type: 'doc', id: 'testing/pytest', className: 'sidebar-icon sidebar-icon--pytest' },
        { type: 'doc', id: 'testing/unittest', className: 'sidebar-icon sidebar-icon--unittest' },
      ] },
    ] },
    { type: 'category', label: 'MCP', className: 'sidebar-icon sidebar-icon--mcp', items: [
      { type: 'doc', id: 'mcp/MCP-Protocol', label: 'Protocol', className: 'sidebar-icon sidebar-icon--mcp' },
      { type: 'doc', id: 'mcp/MCP-CSharp', label: '.NET', className: 'sidebar-icon sidebar-icon--dotnet' },
      { type: 'doc', id: 'mcp/MCP-Python', label: 'Python', className: 'sidebar-icon sidebar-icon--python' },
    ] },
    { type: 'category', label: 'Logging', className: 'sidebar-group sidebar-group--logging', items: [
      { type: 'doc', id: 'logging/Logging-Overview', label: 'Log Level' },
      { type: 'doc', id: 'logging/Observability-Http', label: 'Log Output' },
      { type: 'doc', id: 'logging/Visualization-Overview', label: 'Geometry Visualization' },
    ] },
    { type: 'category', label: 'Hosts', className: 'sidebar-group sidebar-group--hosts', items: [
      { type: 'doc', id: 'hosts/Hosts-Revit', label: 'Revit', className: 'sidebar-icon sidebar-icon--revit' },
      { type: 'doc', id: 'hosts/Hosts-AutoCAD', label: 'AutoCAD', className: 'sidebar-icon sidebar-icon--autocad' },
    ] },
    { type: 'category', label: 'Examples', items: [{ type: 'autogenerated', dirName: 'examples' }] },
    { type: 'category', label: 'Support', items: [
      'getting-started/Troubleshooting',
      'getting-started/Known-Limitations',
      'getting-started/Privacy-And-Telemetry',
      'support/Brand-and-Attribution',
    ] },
  ],
};

export default sidebars;
