<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseRevit>true</UseRevit>
        <ILRepackable>true</ILRepackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Nice3point.Revit.Toolkit" VersionOverride="$(RevitVersion).*"/>
        <PackageReference Include="ModelContextProtocol"/>
        <PackageReference Include="ModelContextProtocol.Extensions.Tasks"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\Content\*.md" />
    </ItemGroup>

</Project>
