name: Compile

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  compile:
    name: Compile
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache packages
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}

      - name: Compile solution
        run: ./.nuke/build.cmd