<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net48;net8.0-windows;net10.0-windows</TargetFrameworks>
        <RootNamespace>DevTools.Testing.Host</RootNamespace>
        <AssemblyName>DevTools.Testing.Host</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="DevTools.Testing.Host.Tests"/>
        <ProjectReference Include="..\DevTools.Testing.Abstractions\DevTools.Testing.Abstractions.csproj"/>
        <ProjectReference Include="..\DevTools.Testing.Transport\DevTools.Testing.Transport.csproj"/>
        <ProjectReference Include="..\DevTools.Ipc\DevTools.Ipc.csproj"/>
    </ItemGroup>
</Project>
